jobs:
  license:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Check License
      uses: apache/skywalking-eyes@main
name: License Check
on:
  repository_dispatch:
    types: trigger-ga___license.yml
permissions:
  contents: read
